#!/bin/bash
#
# Written By: Gabriele Rocca
# Created date: 03-11-2015
# Version: 1.0
#

# lo script deve venir lanciato ogni giorno
# il backup viene esguito nel giorno definito in questo file di configurazione


# giorno in cui eseguire il backup settimanale, se il giorno cade tra 1-7 del mese allora viene eseguito un backup mensile
# indicare Mon Tue Wed Thu Fri Sat Sun
giorno_di_backup='Sun'

spaziominimoStorage="1000000000"
local_mountpoint="/backup"
SHARE='192.168.182.9:/vol/topix/backup-cloud'
destinatari='cloud-alert@top-ix.org'
numerobackup_mensile="2"
numerobackup_settimanale="3"

# invia una trap a zabbix usando zabbix_sender dopo che il backup si conclude (nessuna info su successo, commentare per disabilitare)
#TRAP_ZABBIX_HOST='zabbix02.cloudix' # Hostname or IP address of Zabbix server
#TRAP_HOST='topix-backend01.cloudix' # host name the item belongs to (as registered in Zabbix frontend)
